# -*- coding: utf-8 -*-
"""20-07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WsZrVg2kun8KszxHRvEgdAnimw_spssb
"""

pip install requests

import requests

def shorten_url(long_url):
    """
    Shortens a URL using the TinyURL API.
    """
    api_url = f"https://tinyurl.com/api-create.php?url={long_url}"

    try:
        response = requests.get(api_url, timeout=10)

        if response.status_code == 200:
            return response.text
        else:
            return f"Error: API returned status code {response.status_code}"

    except requests.exceptions.RequestException as e:
        return f"Request failed: {e}"


def main():
    print("=" * 40)
    print("        URL SHORTENER")
    print("=" * 40)

    long_url = input("Enter the URL to shorten: ").strip()

    if not long_url.startswith(("http://", "https://")):
        print("Please enter a valid URL starting with http:// or https://")
        return

    short_url = shorten_url(long_url)

    print("\nOriginal URL:")
    print(long_url)

    print("\nShortened URL:")
    print(short_url)


if __name__ == "__main__":
    main()